### ISSUE TITLE
QR code is invalid

### ISSUE THREAD

**Issue by co63oc** [alibaba/HybridBackend#106]
QR code is invalid

**Comment by 2sin18** [comment]
@co63oc Thanks for your kindly reminding, you can join the chatgroup by using below QR code
![IMG_7015](https://user-images.githubusercontent.com/320794/221529972-4a364c1a-4913-49ef-83be-7c72c5f23651.JPG)

**Comment by 2sin18** [comment]
I would replace QR code in next documentation update.
