### ISSUE TITLE
Training is very slow 

### ISSUE THREAD

**Issue by dixingxing0** [alibaba/HybridBackend#155]
# Current behavior
Training is very slow when using deeprec and hybridbackend for synchronous training.
With 800GB of data, the training is expected to take 60 hours.
We train the same data using horovod about take 12 hours(without deeprec).

Here is the train performance diff with horovod：
![image](https://github.com/DeepRec-AI/HybridBackend/assets/1303530/79b600c3-d89d-43ca-9ad6-a322776524aa)

# Expected behavior

# System information
GPU model and memory: V100 (PCIe),  GPU mem 16GB
OS Platform:
Docker version:
GCC/CUDA/cuDNN version: CUDA 11.7
Python/conda version:
TensorFlow + DeepRec version: 1.15.5+deeprec2306
HybridBackend hybridbackend-deeprec-cu116 1.0.0
# Code to reproduce

```python
```

# Willing to contribute

Yes

**Comment by francktcheng** [comment]
Please describe the workload in more details, such as the GPU type (V100, A100 or others?), are there nvlinks among intra-node GPUs? BTW, I recommend you to run horovod on the same version of deeprec and evaluate the performance as a baseline to compare with hybridbackend.

**Comment by dixingxing0** [comment]
I've add some info:
`GPU model and memory: V100 (PCIe), GPU mem 16GB`

**Comment by dixingxing0** [comment]
@francktcheng I added the performance differences with horovod.

**Comment by dixingxing0** [comment]
After we changed the data format from csv to parquet, the training performance greatly improved. The training speed using a single card has already faster than 4 cards on Horovod. It seems that HB has made corresponding optimizations for the parquet format. The latest test data is as follows:
![image](https://github.com/DeepRec-AI/HybridBackend/assets/1303530/7734fef1-8c27-4faf-9f90-44a4786bc283)

@francktcheng thanks for the advice,  i'will close this issue.
