### ISSUE TITLE
Question: When to release the code?

### ISSUE THREAD

**Issue by gaocegege** [alibaba/HybridBackend#16]
Hi, I saw the code is not public according to the architecture doc here https://hybridbackend.readthedocs.io/en/latest/architecture.html

Do you have a plan to open source it? Or is it just focused on data io?

I'd appreciate it if anyone could help me.

Thanks :clinking_glasses: :beers:

**Comment by gaocegege** [comment]
cc @2sin18

**Comment by 2sin18** [comment]
Thanks for asking. The next major version is planned to release on late Feb, 2022, but no final date has been set yet.
