### ISSUE TITLE
Question: Data Loading Performance with 150G Byte/s

### ISSUE THREAD

**Issue by neuzxy** [alibaba/HybridBackend#22]
Hi, thanks for open source this project，it's a great job！🥂 🍻

I saw the [Data Loading](https://hybridbackend.readthedocs.io/en/latest/tutorials/data_loading.html) doc here，the `ParquetDataset` is to solve IO performance issues on cloud.  

According to the doc,  the speed of reading and decoding `ParquetDataset` is about `150G Byte/s` (3346.10MB/21.67ms) , **equals max throughput of 12X 100G bit/s NIC**,  it's nearly impossible on cloud（hdfs/oss/s3）.
 
File Format | Size (MB) | Framework     | #Threads | Elapsed (ms)
----------- | --------- | ------------- | -------- | ------------
CSV         | 11062.61  | Tensorflow    | 1        | 8558.38
Parquet     | 3346.10   | Tensorflow IO | 1        | 103056.71
Parquet     | 3346.10   | HybridBackend | 1        | 397.88
Parquet     | 3346.10   | HybridBackend | 20       | 21.67

Is it convenient to provide `details` of test environment？
Apart from code of `Dataset` module, will `HybridBackend` engine code be released in the future?

Thanks 🥂 🍻

**Comment by 2sin18** [comment]
Hi, above results are from benchmarks on a local machine with SSD. The workload configuration shown as below:

    | Configuration |     |
    | ---------------- | -- |
    | **CPU** | Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz x 96 |
    | **#iters** | 100 |
    | **#columns** | 200 |
    | **#rows/iter** | 200000 |
    | **MALLOC_CONF** | background_thread:true,metadata_thp:auto |
    | **CSV file size** | 11062.61 MB |
    | **Parquet file size** | 3346.10 MB (with SNAPPY compression) |

The actual throughput is 200000 x 200 x 8 bytes / 21.67ms = 14.08GB/s

**Comment by 2sin18** [comment]
The next major version which includes hybrid parallel training would be released at late Feb.

**Comment by 2sin18** [comment]
Thanks for asking, I would refine the documentation and give more information about the benchmark workload and environment. You can also try the benchmark in your environment too: https://github.com/alibaba/HybridBackend/blob/main/hybridbackend/tools/dataset_benchmark.py

**Comment by neuzxy** [comment]
Thanks for replying.
