### ISSUE TITLE
Feature Request: Supports prefetching data to GPU

### ISSUE THREAD

**Issue by 2sin18** [alibaba/HybridBackend#74]
# User Story

As a recommender system engineer, I want to read large batch of tabular data on GPU efficiently, so that training performance of large deep recommenders can be improved.

# Detailed requirements

- It should be easy to use with TensorFlow Dataset API

# API Compatibility

- Only new APIs should be introduced.

# Willing to contribute

Yes

**Comment by NHZlX** [comment]
大佬，这个有没有和tf 自带 prefetch_to_device的性能比较呢

**Comment by NHZlX** [comment]
@2sin18 Thx~
