### ISSUE TITLE
DLRM model on A100 8cards training

### ISSUE THREAD

**Issue by zhaozheng09** [alibaba/HybridBackend#95]
I don't find a DLRM example in HybridBackend repo.
Can you provid a DLRM example ?

**Comment by 2sin18** [comment]
Hi, there are already DLRM examples for training: https://github.com/alibaba/HybridBackend/blob/main/docs/tutorial/ranking/criteo/train.py

Attention: input dataset is not divided into different slices on different workers in these examples, which would be modified in near future.
